
name: Deployment

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches:
      - develop

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11.0.2
        uses: actions/setup-java@v1
        with:
          java-version: 11.0
      - name: Deploy
        run: mvn -B clean deploy
        env:
          GITHUB_TOKEN: ${{ secrets.MAVEN_CENTRAL_TOKEN }}
